name: CompassPlugin
version: '1.0'
main: me.corruptionsniper.compass.Main
api-version: 1.18
authors: [ CorruptionSniper ]
description: A plugin which provides a compass on the BossBar.
commands:
  settings:
  compassPoints: